src/proxynow5_proj/proxynow5/Dashboard/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('proxynow5_proj.proxynow5.Dashboard.views',
                       (r'^$', 'dashboard_page'),
                       (r'^data/$', 'dashboard_data'),
)

src/proxynow5_proj/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
import os

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
admin.autodiscover()
site_media = os.path.join(settings.DIRNAME, 'media')
site_rept_image = settings.REPORT_PATH_IMAGE

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': site_media}),
                       (r'^rept_image/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': site_rept_image}),
    # Examples:
    # url(r'^$', 'proxynow5_proj.views.home', name='home'),
    # url(r'^proxynow5_proj/', include('proxynow5_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
                        (r'', include('proxynow5_proj.proxynow5.urls')),
                        (r'^setting/', include('proxynow5_proj.proxynow5.Settings.urls')),
                        (r'^dashboard/', include('proxynow5_proj.proxynow5.Dashboard.urls')),
                        (r'^defnet/', include('proxynow5_proj.proxynow5.Definition_Network.urls')),
                        (r'^defuser/', include('proxynow5_proj.proxynow5.Definition_User.urls')),
                        (r'^defservices/', include('proxynow5_proj.proxynow5.Definition_Services.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Administration.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Network.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Definition_Schedule.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Application_Control.urls')),
                        (r'', include('proxynow5_proj.proxynow5.WebProxy.urls')),
                        (r'', include('proxynow5_proj.proxynow5.WebProxy_Filter.urls')),
                        (r'^nat/', include('proxynow5_proj.proxynow5.NAT.urls')),
                        (r'^lic/', include('proxynow5_proj.proxynow5.License.urls')),
                        (r'^log/', include('proxynow5_proj.proxynow5.Log.urls')),
                        (r'^patch/', include('proxynow5_proj.proxynow5.Patch.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Report.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Wizard.urls')),
)

src/proxynow5_proj/proxynow5/Dashboard/models.py
from django.db import models
from django.utils.translation import ugettext as _
from proxynow5_proj.proxynow5.NIC.models import NIC

class Dashboard(models.Model):
    cpu = models.PositiveSmallIntegerField()
    ram = models.PositiveSmallIntegerField()
    swap = models.PositiveSmallIntegerField()
    hd = models.PositiveSmallIntegerField()
    version = models.CharField(max_length=255, unique=True)
    avpattern = models.CharField(max_length=255)
    request = models.PositiveIntegerField()
    block = models.PositiveIntegerField()
    malware = models.PositiveIntegerField()
    
    class Meta:
        db_table = 'Dashboard'
    
class DashboardNIC(models.Model):
    name = models.CharField(max_length=1024, unique=True)
    status = models.CharField(max_length=4)
    inbw = models.DecimalField(max_digits=12, decimal_places=2)
    outbw = models.DecimalField(max_digits=12, decimal_places=2)
    
    def get_nic_by_name(self):
        o = NIC.objects.get(name__iexact=self.name)
        return o
    
    def get_netint_name(self):
        o = self.get_nic_by_name()
        x = o.netint_set.get(hardware=o)
        return x.name
    
    def get_netint_type(self):
        o = self.get_nic_by_name()
        x = o.netint_set.get(hardware=o)
        return x.get_type_name()
    
    class Meta:
        db_table = 'DashboardNIC'
        ordering = ['name']

src/proxynow5_proj/proxynow5/Dashboard/forms.py
from django import forms
from django.utils.translation import ugettext as _

REFRESH_CHOICES = (
                   (0, _(u'Never')),
                   (5, _(u'Every 5 seconds')),
                   (10, _(u'Every 10 seconds')),
                   (30, _(u'Every 30 seconds')),
                   (60, _(u'Every 60 seconds')),
)

class RefreshForm(forms.Form):
    refresh = forms.ChoiceField(choices=REFRESH_CHOICES, initial=5,
                                widget=forms.Select(attrs={'class': 'select'}))

src/proxynow5_proj/proxynow5/Dashboard/views.py
from django.http import *
from django.shortcuts import *
from forms import *
from models import *
from proxynow5_proj.proxynow5.utils import *
from proxynow5_proj.proxynow5.resourceutils import *
from proxynow5_proj.proxynow5.License.license import *
from proxynow5_proj.proxynow5.License.models import License
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.utils.translation import ugettext as _
from django.template.loader import get_template
from datetime import datetime

@login_required
@admin_access_required
def dashboard_page(request):
    currdate, dashboard, niclist = get_dashboard_info()
    lic = get_license_status()
    form = RefreshForm()
    hd_info = GetHD()
    swap_info = GetSwapMem()
    ram_info = GetPhysicalMem()
    cpu_info = GetCPU(value=False)
    ram_total = get_total_ram(ram_info)
    swap_total = get_total_swap(swap_info)
    hd_total = get_total_hd(hd_info)
    if dashboard is None:
        dashboard = Dashboard(cpu=cpu_info, ram=ram_info[1], swap=swap_info[1], hd=hd_info[1],
                              version='', avpattern='', request=0, block=0, malware=0)
    variables = RequestContext(request, {'title': _(u'Dashboard for'),
                                         'currdate': currdate,
                                         'form': form,
                                         'dashboard': dashboard,
                                         'lic': lic,
                                         'ram_total': ram_total,
                                         'swap_total': swap_total,
                                         'hd_total': hd_total,
                                         'niclist': niclist})
    return render_to_response('dashboard/dashboard_page.html', variables)

@login_required
@admin_access_required
def dashboard_data(request):
    currdate, o, niclist = get_dashboard_info()
    t = get_template('dashboard/dashboard_nic_list.html')
    nic = t.render(RequestContext(request, {'niclist': niclist}))
    dic = None
    try:
        info = get_resource_info()
        if o == None:
            dic = {'currdate': currdate,
                   'cpu': info['cpu'],
                   'ram': info['ram'],
                   'swap': info['swap'],
                   'hd': info['hd'],
                   'avpattern': '',
                   'request': 0,
                   'block': 0,
                   'malware': 0,
                   'niclist': nic}
            
        else:
            dic = {'currdate': currdate,
                   'cpu': info['cpu'],
                   'ram': info['ram'],
                   'swap': info['swap'],
                   'hd': info['hd'],
                   'avpattern': o.avpattern,
                   'request': o.request,
                   'block': o.block,
                   'malware': o.malware,
                   'niclist': nic}
        
    except Exception as err:
        dic = {'currdate': currdate,
               'error': 1}
        print err
        
    print dic
    return json_result(dic)

def get_dashboard_info():
    datenow = datetime.now()
    currdate = datenow.strftime('%a %b %d %H:%M:%S %Y')
    dashboard = None
    dashboardcount = 0
    try:
        dashboardcount = Dashboard.objects.count()
        
    except:
        pass
    
    if dashboardcount > 0:
        dashboard = Dashboard.objects.all()[0]
        
    niclist = DashboardNIC.objects.all()
    return currdate, dashboard, niclist

def get_resource_info():
    hd_info = GetHD()
    swap_info = GetSwapMem()
    ram_info = GetPhysicalMem()
    cpu_info = GetCPU()
    print hd_info
    print ram_info
    print cpu_info
    
    dic = {'cpu': cpu_info,
           'ram': ram_info[1],
           'swap': swap_info[1],
           'hd': hd_info[1]}
    
    print dic 
    
    return dic

def get_license_status():
    dic = {}
    statusmsg = _(u'Not activated')
    try:
        o = License.objects.all()[0]
        info, msg = get_license_info(o.activationkey, o.identitytoken, None)
        if info['PN_EXPIRY_DATE'] != statusmsg:
            statusmsg = _(u'Activated')
            dic = {'status': statusmsg,
                   'basesoftware': info['PN_EXPIRY_DATE'],
                   'webproxy': info['PN_WEBPROXY_EXPIRY_DATE']}
            
        else:
            dic = {'status': statusmsg,
                   'basesoftware': statusmsg,
                   'webproxy': statusmsg}
        
    except:
        dic = {'status': statusmsg,
               'basesoftware': statusmsg,
               'webproxy': statusmsg}
        
    return dic

def get_license_info(key, token, conn=None):
    _conn = None
    info = {}
    msg = ''
    try:
        if conn is None:
            _conn = connect()
            
        else:
            _conn = conn
            
        _info, msg = read_info(_conn, key, token)
        info = convert_info(_info)
        
    except:
        info = get_default_info(key, token)
        
    finally:
        if conn is None:
            close_connection(_conn)
            
    return info, msg

def convert_info(info):
    dic = {'ActivationKey': info['ActivationKey'],
           'IdentityToken': info['IdentityToken'],
           'PN_EXPIRY_DATE': get_fmt_date(info['PN_EXPIRY_DATE']),
           'PN_WEBPROXY_EXPIRY_DATE': get_fmt_date(info['PN_WEBPROXY_EXPIRY_DATE']),
           'DateOfActivation': get_fmt_datetime(info['DateOfActivation']),
           'PN_No_of_Users': int(info['PN_No_of_Users']),
           'PN_RESERVED1_EXPIRY_DATE': get_fmt_datetime(info['PN_RESERVED1_EXPIRY_DATE']),
           'PN_RESERVED2_EXPIRY_DATE': get_fmt_datetime(info['PN_RESERVED2_EXPIRY_DATE']),
           'PN_RESERVED3_EXPIRY_DATE': get_fmt_datetime(info['PN_RESERVED3_EXPIRY_DATE']),
           'PN_RESERVED4_EXPIRY_DATE': get_fmt_datetime(info['PN_RESERVED4_EXPIRY_DATE']),
           'PN_RESERVED5_EXPIRY_DATE': get_fmt_datetime(info['PN_RESERVED5_EXPIRY_DATE']),
           'ORG_PN_EXPIRY_DATE': get_datetime_from_dbstr(info['PN_EXPIRY_DATE'])}
    return dic

def get_total_ram(ram_info):
    try:
        val = ram_info[0]
        v = round(val / 1048576, 1)
        return '%s MB' % v
    
    except:
        return '0 MB'
    
def get_total_swap(swap_info):
    try:
        val = swap_info[0]
        v = round(val / 1048576, 1)
        return '%s MB' % v
    
    except:
        return '0 MB'

def get_total_hd(hd_info):
    try:
        val = hd_info[0]
        v = round(val / 1073741824, 1)
        return '%s GB' % v
    
    except:
        return '0 GB'

src/proxynow5_proj/templates/dashboard/dashboard_license.html
{% load i18n %}
<table class="dashboard_tbl1 ui-widget-content">
	<thead class="ui-widget-header">
		<tr>
			<th colspan="2">{% trans 'License' %}</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="collbl lic">{% trans 'Status:' %}</td>
			<td><span id="id_licstatus">{{ lic.status }}</span></td>
		</tr>
		<tr>
			<td class="collbl lic">{% trans 'Base software:' %}</td>
			<td><span id="id_licbasesw">{{ lic.basesoftware }}</span></td>
		</tr>
		<tr>
			<td class="collbl lic">{% trans 'Web proxy:' %}</td>
			<td><span id="id_licwebproxy">{{ lic.webproxy }}</span></td>
		</tr>
	</tbody>
</table>

src/proxynow5_proj/templates/dashboard/dashboard_nic.html
{% load i18n %}
<table class="dashboard_tbl2 ui-widget-content">
	<thead class="ui-widget-header">
		<th align="justify">{% trans 'Port' %}</th>
		<th align="justify">{% trans 'Name' %}</th>
		<th align="justify">{% trans 'Type' %}</th>
		<th align="justify">{% trans 'Status' %}</th>
		<th align="right" width="100px">{% trans 'In' %}</th>
		<th align="right" width=100px">{% trans 'Out' %}</th>
	</thead>
	<tbody>
	{% include "dashboard/dashboard_nic_list.html" %}
	</tbody>
</table>

src/proxynow5_proj/templates/dashboard/dashboard_nic_list.html
{% for o in niclist %}
	<tr>
		<td>{{ o.name }}</td>
		<td>{{ o.get_netint_name }}</td>
		<td>{{ o.get_netint_type }}</td>
		<td>
		{% if o.status|lower == "up" %}
			<strong><span style="color: green">{{ o.status }}</span></strong>
		{% else %}
			<strong><span style="color: red">{{ o.status }}</span></strong>
		{% endif %}
		</td>
		<td>
			<div id="id_pgbarinbw" class="ui-progressbar ui-widget ui-widget-content dashboardnic_pgbar_outer">
				<div class="dashboardnic_pgbar_text">{{ o.inbw }} Kbps</div>
			</div>
		</td>
		<td>
			<div id="id_pgbaroutbw" class="ui-progressbar ui-widget ui-widget-content dashboardnic_pgbar_outer">
				<div class="dashboardnic_pgbar_text">{{ o.outbw }} Kbps</div>
			</div>
		</td>
	</tr>
{% endfor %}

src/proxynow5_proj/templates/dashboard/dashboard_page.html
{% load i18n %}
<div id="table_container">
	<div class="page_title ui-widget-header ui-widget">{{ title }}
		&nbsp;<span id="id_currdate" class="dashboard_date">{{ currdate }}</span>
		<div class="dashboard_refresh">
			<label for="id_refresh">{% trans 'Refresh:' %}</label>
			{{ form.refresh }}
		</div>
	</div>
	<table class="dashboard_tbl ui-widget">
		<tbody>
			<tr>
				<td class="col">
					{% include "dashboard/dashboard_version.html" %}
					{% include "dashboard/dashboard_resource.html" %}
					{% include "dashboard/dashboard_statistic.html" %}
					{% include "dashboard/dashboard_license.html" %}
				</td>
				<td class="col">
					{% include "dashboard/dashboard_nic.html" %}
				</td>
			</tr>
		</tbody>
	</table>
</div>

src/proxynow5_proj/templates/dashboard/dashboard_resource.html
{% load i18n %}
<table class="dashboard_tbl1 ui-widget-content">
	<thead class="ui-widget-header">
		<tr>
			<th colspan="2">{% trans 'Resource usage' %}</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="collbl resource">{% trans 'CPU' %}<span class="proxynow cpuicon spaceiconlist"></span></td>
			<td>
				<div id="id_pgbarcpu" class="ui-progressbar ui-widget ui-widget-content dashboard_pgbar_outer">
					<div class="ui-progressbar-value ui-state-hover" style="width: {{ dashboard.cpu }}%">
						<div class="dashboard_pgbar_text">{{ dashboard.cpu }}%</div>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td class="collbl resource">{% trans 'RAM' %}<span class="proxynow ramicon spaceiconlist"></span></td>
			<td>
				<div id="id_pgbarram" class="ui-progressbar ui-widget ui-widget-content dashboard_pgbar_outer">
					<div class="ui-progressbar-value ui-state-hover" style="width: {{ dashboard.ram }}%">
						<div class="dashboard_pgbar_text"><span class="ram_val">{{ dashboard.ram }}%</span>&nbsp;{% trans 'of' %}&nbsp;<span class="ram_total">{{ ram_total }}</span></div>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td class="collbl resource">{% trans 'Swap' %}<span class="proxynow swapicon spaceiconlist"></span></td>
			<td>
				<div id="id_pgbarswap" class="ui-progressbar ui-widget ui-widget-content dashboard_pgbar_outer">
					<div class="ui-progressbar-value ui-state-hover" style="width: {{ dashboard.swap }}%">
						<div class="dashboard_pgbar_text"><span class="swap_val">{{ dashboard.swap }}%</span>&nbsp;{% trans 'of' %}&nbsp;<span class="swap_total">{{ swap_total }}</span></div>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td class="collbl resource">{% trans 'HD' %}<span class="proxynow hdicon spaceiconlist"></span></td>
			<td>
				<div id="id_pgbarhd" class="ui-progressbar ui-widget ui-widget-content dashboard_pgbar_outer">
					<div class="ui-progressbar-value ui-state-hover" style="width: {{ dashboard.hd }}%">
						<div class="dashboard_pgbar_text"><span class="hd_val">{{ dashboard.hd }}%</span>&nbsp;{% trans 'of' %}&nbsp;<span class="hd_total">{{ hd_total }}</span></div>
					</div>
				</div>
			</td>
		</tr>
	</tbody>
</table>

src/proxynow5_proj/templates/dashboard/dashboard_statistic.html
{% load i18n %}
<table class="dashboard_tbl1 ui-widget-content">
	<thead class="ui-widget-header">
		<tr>
			<th colspan="2">{% trans 'Today statistic' %}</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="collbl statistic">{% trans 'Request:' %}</td>
			<td><span id="id_request">{{ dashboard.request }}</span></td>
		</tr>
		<tr>
			<td class="collbl statistic">{% trans 'Block:' %}</td>
			<td><span id="id_block">{{ dashboard.block }}</span></td>
		</tr>
		<tr>
			<td class="collbl statistic">{% trans 'Malware:' %}</td>
			<td><span id="id_malware">{{ dashboard.malware }}</span></td>
		</tr>
	</tbody>
</table>

src/proxynow5_proj/templates/dashboard/dashboard_version.html
{% load i18n %}
<table class="dashboard_tbl1 ui-widget-content">
	<thead class="ui-widget-header">
		<tr>
			<th colspan="2">{% trans 'Version information' %}</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="collbl version">{% trans 'Firmware version:' %}</td>
			<td><span>{{ dashboard.version }}</span></td>
		</tr>
		<tr>
			<td class="collbl version">{% trans 'Antivirus pattern date:' %}</td>
			<td><span id="id_avpattern">{{ dashboard.avpattern }}</span></td>
		</tr>
	</tbody>
</table>