src/proxynow5_proj/proxynow5/NAT/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('proxynow5_proj.proxynow5.NAT.views',
                       (r'^$', 'nat_page'),
                       
                       (r'^pf/$', 'natpf_page'),
                       (r'^pf/save/$', 'natpf_save'),
                       (r'^pf/delete/$', 'natpf_delete'),
                       (r'^pf/list/$', 'natpf_list'),
                       
                       (r'^masq/$', 'natmasq_page'),
                       (r'^masq/save/$', 'natmasq_save'),
                       (r'^masq/delete/$', 'natmasq_delete'),
                       (r'^masq/save/location/$', 'natmasq_save_location'),
                       (r'^masq/list/$', 'natmasq_list'),
                       
                       (r'^dnatsnat/$', 'natdnatsnat_page'),
                       (r'^dnatsnat/save/$', 'natdnatsnat_save'),
                       (r'^dnatsnat/delete/$', 'natdnatsnat_delete'),
                       (r'^dnatsnat/list/$', 'natdnatsnat_list'),
)

src/proxynow5_proj/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
import os

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
admin.autodiscover()
site_media = os.path.join(settings.DIRNAME, 'media')
site_rept_image = settings.REPORT_PATH_IMAGE

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': site_media}),
                       (r'^rept_image/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': site_rept_image}),
    # Examples:
    # url(r'^$', 'proxynow5_proj.views.home', name='home'),
    # url(r'^proxynow5_proj/', include('proxynow5_proj.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
                        (r'', include('proxynow5_proj.proxynow5.urls')),
                        (r'^setting/', include('proxynow5_proj.proxynow5.Settings.urls')),
                        (r'^dashboard/', include('proxynow5_proj.proxynow5.Dashboard.urls')),
                        (r'^defnet/', include('proxynow5_proj.proxynow5.Definition_Network.urls')),
                        (r'^defuser/', include('proxynow5_proj.proxynow5.Definition_User.urls')),
                        (r'^defservices/', include('proxynow5_proj.proxynow5.Definition_Services.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Administration.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Network.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Definition_Schedule.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Application_Control.urls')),
                        (r'', include('proxynow5_proj.proxynow5.WebProxy.urls')),
                        (r'', include('proxynow5_proj.proxynow5.WebProxy_Filter.urls')),
                        (r'^nat/', include('proxynow5_proj.proxynow5.NAT.urls')),
                        (r'^lic/', include('proxynow5_proj.proxynow5.License.urls')),
                        (r'^log/', include('proxynow5_proj.proxynow5.Log.urls')),
                        (r'^patch/', include('proxynow5_proj.proxynow5.Patch.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Report.urls')),
                        (r'', include('proxynow5_proj.proxynow5.Wizard.urls')),
)

src/proxynow5_proj/proxynow5/NAT/models.py
from django.db import models
from django.utils.translation import ugettext as _
from proxynow5_proj.proxynow5.Network.models import NetInt
from proxynow5_proj.proxynow5.Definition_Services.models import DefServices
from proxynow5_proj.proxynow5.Definition_Network.models import DefNet

NAT_DNAT_SNAT_MODES = (
                       (1, _(u'DNAT')),
                       (2, _(u'SNAT')),
                       (3, _(u'Both'))
)

class NAT_PF(models.Model):
    interface = models.ForeignKey(NetInt, db_column='interface',
                                  verbose_name=_(u'Interface'))
    originalPort = models.ForeignKey(DefServices, related_name='natpforiginalports', db_column='originalPort',
                                     verbose_name=_(u'Port'))
    host = models.ForeignKey(DefNet, related_name='natpfhosts', db_column='host',
                             verbose_name=_(u'Host'))
    newService = models.ForeignKey(DefServices, related_name='natpfnewservices', db_column='newService',
                                   verbose_name=_(u'Port'))
    comment = models.TextField(max_length=10240, blank=True, 
                               verbose_name=_(u'Comment'))
    
    class Meta:
        db_table = 'NAT_PF'
        
class NAT_MASQ(models.Model):
    network = models.ForeignKey(DefNet, db_column='network',
                                verbose_name=_(u'Network'))
    interface = models.ForeignKey(NetInt, related_name='natmasqinterfaces', db_column='interface',
                                  verbose_name=_(u'Interface'))
    location = models.PositiveIntegerField(verbose_name=_(u'Location'))
    comment = models.TextField(max_length=10240, blank=True, 
                               verbose_name=_(u'Comment'))
    
    class Meta:
        db_table = 'NAT_MASQ'
        ordering = ['location']
        
class NAT_DNAT_SNAT(models.Model):
    originalSource = models.ForeignKey(DefNet, db_column='originalSource',
                                       verbose_name=_(u'Original source'))
    originalPort = models.ForeignKey(DefServices, related_name='natdnatsnatoriginalports', db_column='originalPort',
                                     verbose_name=_(u'Original port'))
    originalDestination = models.ForeignKey(DefNet, related_name='natdnatsnatoriginaldestinations', db_column='originalDestination',
                                            verbose_name=_(u'Original destination'))
    mode = models.PositiveSmallIntegerField(verbose_name=_(u'NAT mode'))
    newDestinationHost = models.ForeignKey(DefNet, related_name='natdnatsnatnewdestinationhosts', db_column='newDestinationHost', null=True,
                                           verbose_name=_(u'New destination'))
    newDestinationPort = models.ForeignKey(DefServices, related_name='natdnatsnatnewdestinationports', db_column='newDestinationPort', null=True,
                                           verbose_name=_(u'New destination port'))
    newSourceAddress = models.ForeignKey(DefNet, related_name='natdnatsnatnewsourceaddresses', db_column='newSourceAddress', null=True,
                                         verbose_name=_(u'New source'))
    newSourcePort = models.ForeignKey(DefServices, related_name='natdnatsnatnewsourceports', db_column='newSourcePort', null=True,
                                      verbose_name=_(u'New source port'))
    autoCreatePFRule = models.PositiveSmallIntegerField(default=1, verbose_name=_(u'Automatically open on packet filter'))
    comment = models.TextField(max_length=10240, blank=True, 
                               verbose_name=_(u'Comment'))
    
    def get_mode_name(self):
        if self.mode >= 1 <= 3:
            return NAT_DNAT_SNAT_MODES[self.mode - 1][1]
        
        return ''
    
    class Meta:
        db_table = 'NAT_DNAT_SNAT'

src/proxynow5_proj/proxynow5/NAT/views.py
from django.http import *
from django.shortcuts import *
from forms import *
from models import *
from search import *
from proxynow5_proj.proxynow5.utils import *
from proxynow5_proj.proxynow5.sortablelist import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, InvalidPage
from django.template.context import RequestContext
from django.utils.translation import ugettext as _
from proxynow5_proj.proxynow5.forms import NavigateForm
from proxynow5_proj.proxynow5.exceptions import UIException
from django.template.loader import get_template
from django.db import transaction

@login_required
@admin_access_required
def nat_page(request):
    variables = RequestContext(request)
    return render_to_response('nat/nat_page.html', variables)

#===============================================================================
# Port forwarding
#===============================================================================
@login_required
@admin_access_required
def natpf_save(request):
    form_title = ADD_NAT_PF_FORM_TITLE
    if request.method == 'POST':
        form = NAT_PFForm(request.POST)
        if form.is_valid():
            try:
                if request.is_ajax():
                    form.save(request)
                    return HttpResponse(u'success')
                
                else:
                    return HttpResponseRedirect('/nat/pf/save/')
                
            except UIException, e:
                return HttpResponse(e)
            
        else:
            return json_form_error(form)
        
    elif 'id' in request.GET:
        form_title = EDIT_NAT_PF_FORM_TITLE
        id = request.GET['id']
        clone = ''
        if 'clone' in request.GET:
            clone = request.GET['clone']
            form_title = ADD_NAT_PF_FORM_TITLE
            
        try:
            o = NAT_PF.objects.get(id=id)
            interface = o.interface
            comment = o.comment
            dic = {'interface': interface,
                   'comment': comment}
            form = NAT_PFForm(dic)
            variables = RequestContext(request, {'form': form,
                                                 'o': o,
                                                 'form_title': form_title,
                                                 'dialog1_title': _(u'Add service definition'),
                                                 'dialog1_edit_title': _(u'Edit service definition'),
                                                 'dialog2_title': _(u'Add network definition'),
                                                 'dialog2_edit_title': _(u'Edit network definition'),
                                                 'dialog3_title': _(u'Add service definition'),
                                                 'dialog3_edit_title': _(u'Edit service definition')})
            return render_to_response('nat/natpf_save_form.html', variables)
            
        except NAT_PF.DoesNotExist:
            pass
        
    else:
        form = NAT_PFForm()
        
    variables = RequestContext(request, {'form': form,
                                         'form_title': form_title,
                                         'dialog1_title': _(u'Add service definition'),
                                         'dialog1_edit_title': _(u'Edit service definition'),
                                         'dialog2_title': _(u'Add network definition'),
                                         'dialog2_edit_title': _(u'Edit network definition'),
                                         'dialog3_title': _(u'Add service definition'),
                                         'dialog3_edit_title': _(u'Edit service definition')})
    return render_to_response('nat/natpf_save_form.html', variables)

@login_required
@admin_access_required
@transaction.commit_on_success
def natpf_delete(request):
    if request.method == 'POST':
        if 'id' in request.POST:
            id = request.POST['id']
            pgsize = int(request.POST['pgsize'])
            pgnum = int(request.POST['pgnum'])
            keyword = request.POST.get('text', '')
            try:
                o = NAT_PF.objects.get(id=id)
                
            except NAT_PF.DoesNotExist:
                return HttpResponse(u'invalid id')
            
            o.delete()
            if keyword != '':
                q = get_natpf_query(keyword)
                total = NAT_PF.objects.filter(q).count()
                
            else:
                total = NAT_PF.objects.count()
                
            if total < pgsize or pgsize < 1:
                pgsize = total
        
            s = get_item_msg(total, pgsize, pgnum)
            if request.is_ajax():
                return HttpResponse(u'success|%s' % s)
            
            else:
                return HttpResponseRedirect('/nat/pf/')
            
    return HttpResponse(u'invalid id')

@login_required
@admin_access_required
def natpf_list(request):
    template = 'nat/natpf_list.html'
    return process_natpf(request, template)

@login_required
@admin_access_required
def natpf_page(request):
    dic = {
           'title': _(u'Port Forwarding'),
           'searchform': NATSearchForm(),
           'hide_search_selection': True,
           'template': 'nat/natpf_page.html',
           'add_label': _(u'New port forwarding ...'),
           'dialog_title': _(u'Edit port forwarding')
           }
    return get_page_list(request, NAT_PF, dic)

#===============================================================================
# Masquerading
#===============================================================================
@login_required
@admin_access_required
def natmasq_save(request):
    form_title = ADD_NAT_MASQ_FORM_TITLE
    if request.method == 'POST':
        form = NAT_MASQForm(request.POST)
        if form.is_valid():
            try:
                if request.is_ajax():
                    form.save(request)
                    return HttpResponse(u'success')
                
                else:
                    return HttpResponseRedirect('/nat/masq/save/')
                
            except UIException, e:
                return HttpResponse(e)
            
        else:
            return json_form_error(form)
        
    elif 'id' in request.GET:
        form_title = EDIT_NAT_MASQ_FORM_TITLE
        id = request.GET['id']
        clone = ''
        if 'clone' in request.GET:
            clone = request.GET['clone']
            form_title = ADD_NAT_MASQ_FORM_TITLE
            
        try:
            o = NAT_MASQ.objects.get(id=id)
            interface = o.interface
            location = o.location
            comment = o.comment
            dic = {'interface': interface,
                   'location': location,
                   'comment': comment}
            form = NAT_MASQForm(dic)
            variables = RequestContext(request, {'form': form,
                                                 'o': o,
                                                 'form_title': form_title,
                                                 'dialog1_title': _(u'Add network definition'),
                                                 'dialog1_edit_title': _(u'Edit network definition')})
            return render_to_response('nat/natmasq_save_form.html', variables)

        except NAT_MASQ.DoesNotExist:
            pass
        
    else:
        form = NAT_MASQForm()
        
    variables = RequestContext(request, {'form': form,
                                         'form_title': form_title,
                                         'dialog1_title': _(u'Add network definition'),
                                         'dialog1_edit_title': _(u'Edit network definition')})
    return render_to_response('nat/natmasq_save_form.html', variables)

@login_required
@admin_access_required
@transaction.commit_on_success
def natmasq_delete(request):
    if request.method == 'POST':
        if 'id' in request.POST:
            id = request.POST['id']
            pgsize = int(request.POST['pgsize'])
            pgnum = int(request.POST['pgnum'])
            keyword = request.POST.get('text', '')
            try:
                o = NAT_MASQ.objects.get(id=id)
                
            except NAT_MASQ.DoesNotExist:
                return HttpResponse(u'invalid id')
            
            loc = o.location
            ls = NAT_MASQ.objects.order_by('location')
            tls = tuple(ls)
            o.delete()
            update_locations_after_delete(loc, tls)
            if keyword != '':
                q = get_natmasq_query(keyword)
                total = NAT_MASQ.objects.filter(q).count()
                
            else:
                total = NAT_MASQ.objects.count()
                
            if total < pgsize or pgsize < 1:
                pgsize = total
        
            s = get_item_msg(total, pgsize, pgnum)
            if request.is_ajax():
                return HttpResponse(u'success|%s' % s)
            
            else:
                return HttpResponseRedirect('/nat/masq/')
            
    return HttpResponse(u'invalid id')

@login_required
@admin_access_required
@transaction.commit_on_success
def natmasq_save_location(request):
    if request.method == 'POST':
        if 'id' in request.POST:
            _id = request.POST['id']
            _swapid = request.POST['swapid']
            id = int(_id)
            swapid = int(_swapid)
            
            try:
                o = NAT_MASQ.objects.get(id=id)
                x = NAT_MASQ.objects.get(id=swapid)
                
            except NAT_MASQ.DoesNotExist:
                return HttpResponse(u'invalid id')
            
            old_loc = o.location
            new_loc = x.location
            ls = NAT_MASQ.objects.order_by('location')
            tls = tuple(ls)
            

src/proxynow5_proj/templates/nat/nat_page.html
{% load i18n %}
<div id="nat_tabs">
	<ul>
		<li><a href="/nat/pf/" title="nat1">{% trans 'Port Forwarding' %}</a></li>
		<li><a href="/nat/masq/" title="nat2">{% trans 'Masquerading' %}</a></li>
		<li><a href="/nat/dnatsnat/" title="nat3">{% trans 'DNAT/SNAT' %}</a></li>
	</ul>
</div>

src/proxynow5_proj/templates/nat/natdnatsnat_list.html
{% load i18n %}
{% if objlist %}
	<table class="list_table">
		<tbody>
		{% for o in objlist %}
			<tr class="{% cycle 'ui-state-default' 'ui-state-hover' %} list_row">
				<td id="{{ o.id }}" width="60px" valign="top">
					{% include "list_button.html" %}
				</td>
				<td valign="top">
					<div class="row_dnatsnat">
						<label><strong>{{ o.get_mode_name }}</strong></label>
					</div>
					<div class="row_dnatsnat">
						<label>{% trans 'Original source:' %}</label>
						{{ o.originalSource.get_html_repr }}
					</div>
					<div class="row_dnatsnat">
						<label>{% trans 'Original port:' %}</label>
						{{ o.originalPort.get_html_repr }}
					</div>
					<div class="row_dnatsnat">
						<label>{% trans 'Original destination:' %}</label>
						{{ o.originalDestination.get_html_repr }}
					</div>
					{% if o.mode == 1 or o.mode == 3 %}
					<div class="row_dnatsnat">
						<label>{% trans 'New destination:' %}</label>
						{{ o.newDestinationHost.get_html_repr }}
					</div>
					<div class="row_dnatsnat">
						<label>{% trans 'New destination port:' %}</label>
						{{ o.newDestinationPort.get_html_repr }}
					</div>
					{% else %}{% if o.mode == 2 or o.mode == 3 %}
					<div class="row_dnatsnat">
						<label>{% trans 'New source:' %}</label>
						{{ o.newSourceAddress.get_html_repr }}
					</div>
					<div class="row_dnatsnat">
						<label>{% trans 'New source port:' %}</label>
						{{ o.newSourcePort.get_html_repr }}
					</div>
					{% endif %}{% endif %}
					<div class="row_dnatsnat">
						<label>{% trans 'Automatically open on packet filter:' %}</label>
						{% if o.autoCreatePFRule == 1 %}
						<span class="proxynow posticon spaceiconlist"></span>
						{% else %}
						<span class="proxynow deleteicon spaceisonlist"></span>
						{% endif %}
					</div>
					{% if o.comment %}
					<br>
					{{ o.comment }}
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}
<input id="id_pg" type="hidden" value="{{ has_prev }},{{ has_next }},{{ prev_page }},{{ next_page }},{{item_msg }}" />

src/proxynow5_proj/templates/nat/natdnatsnat_page.html
{% extends "base_list_page.html" %}
{% load i18n %}
{% block content %}
	{% include "nat/natdnatsnat_list.html" %}
	{% include "list_panel.html" %}
{% endblock %}

src/proxynow5_proj/templates/nat/natmasq_list.html
{% load i18n %}
{% if objlist %}
	<table class="list_table">
		<tbody>
		{% for o in objlist %}
			<tr class="{% cycle 'ui-state-default' 'ui-state-hover' %} list_row">
				<td id="{{ o.id }}" width="60px">
					{% include "list_button.html" %}
				</td>
				<td valign="top">
					<strong>{{ o.location }}</strong>
				</td>
				<td valign="top">
					{{ o.network.get_html_repr }} --&gt; {{ o.interface.name }} 
					{% if o.comment %}
					<br>
					{{ o.comment }}
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}
<input id="id_pg" type="hidden" value="{{ has_prev }},{{ has_next }},{{ prev_page }},{{ next_page }},{{item_msg }}" />

src/proxynow5_proj/templates/nat/natmasq_page.html
{% extends "base_list_page.html" %}
{% load i18n %}
{% block content %}
	{% include "nat/natmasq_list.html" %}
	{% include "list_panel.html" %}
{% endblock %}

src/proxynow5_proj/templates/nat/natmasq_save_form.html
{% load i18n %}
{% include "save_form_title.html" %}
<div class="ui-widget-content ui-widget ui-corner-all">
	<form id="save-form" action="/nat/masq/save/" method="post">{% csrf_token %}
		<div class="row">
			{{ form.network.label_tag }}
			<div class="nat_dropzone">
				<div id="network">
					<div class="img_add proxynow addicon"></div>
					<div class="img_folder proxynow foldericon"></div>
				</div>
				<div id="id_network" class="nat_box">
					{% if o.network %}
					<div id="network_{{ o.network.id }}" class="list_item">
						<div class="proxynow trashicon item_delete" onclick="return natmasq.remove_network(this)"></div>
						<div class="proxynow editicon item_edit" onclick="return natmasq.edit_network(this)"></div>
						<div>{{ o.network.get_html_repr }}</div>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="row">
			{{ form.interface.label_tag }}
			{{ form.interface }}
		</div>
		<div class="row">
			{{ form.location.label_tag }}
			{{ form.location }}
		</div>
		<div class="row">
			{{ form.comment.label_tag }}
			{{ form.comment }}
		</div>
		{% include "save_button.html" %}
		<div id="dialog-add-network" title="{{ dialog1_title }}">
			<div id="dialog_body-network"></div>
		</div>
		<div id="dialog-edit-network" title="{{ dialog1_edit_title }}">
			<div id="dialog_edit_body-network"></div>
		</div>
	</form>
</div>

src/proxynow5_proj/templates/nat/natpf_list.html
{% load i18n %}
{% if objlist %}
	<table class="list_table">
		<tbody>
		{% for o in objlist %}
			<tr class="{% cycle 'ui-state-default' 'ui-state-hover' %} list_row">
				<td id="{{ o.id }}" width="60px">
					{% include "list_button.html" %}
				</td>
				<td valign="top">
					{{ o.interface.name }} --&gt;
					{{ o.originalPort.get_html_repr }}
					{{ o.host.get_html_repr }}
					{{ o.newService.get_html_repr }}
					{% if o.comment %}
					<br>
					{{ o.comment }}
					{% endif %}
				</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endif %}
<input id="id_pg" type="hidden" value="{{ has_prev }},{{ has_next }},{{ prev_page }},{{ next_page }},{{item_msg }}" />

src/proxynow5_proj/templates/nat/natpf_page.html
{% extends "base_list_page.html" %}
{% load i18n %}
{% block content %}
	{% include "nat/natpf_list.html" %}
	{% include "list_panel.html" %}
{% endblock %}

src/proxynow5_proj/templates/nat/natpf_save_form.html
{% load i18n %}
{% include "save_form_title.html" %}
<div class="ui-widget-content ui-widget ui-corner-all">
	<form id="save-form" action="/nat/pf/save/" method="post">{% csrf_token %}
		<div class="row">
			{{ form.interface.label_tag }}
			{{ form.interface }}
		</div>
		<div class="row">
			{{ form.originalPort.label_tag }}
			<div class="nat_dropzone">
				<div id="orgport">
					<div class="img_add proxynow addicon"></div>
					<div class="img_folder proxynow foldericon"></div>
				</div>
				<div id="id_originalport" class="nat_box">
					{% if o.originalPort %}
					<div id="orgport_{{ o.originalPort.id }}" class="list_item">
						<div class="proxynow trashicon item_delete" onclick="return natpf.remove_originalport(this)"></div>
						<div class="proxynow editicon item_edit" onclick="return natpf.edit_originalport(this)"></div>
						<div>{{ o.originalPort.get_html_repr }}</div>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<hr/>
		<div class="row">
			{{ form.host.label_tag }}
			<div class="nat_dropzone">
				<div id="host">
					<div class="img_add proxynow addicon"></div>
					<div class="img_folder proxynow foldericon"></div>
				</div>
				<div id="id_host" class="nat_box">
					{% if o.host %}
					<div id="host_{{ o.host.id }}" class="list_item">
						<div class="proxynow trashicon item_delete" onclick="return natpf.remove_host(this)"></div>
						<div class="proxynow editicon item_edit" onclick="return natpf.edit_host(this)"></div>
						<div>{{ o.host.get_html_repr }}</div>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="row">
			{{ form.newService.label_tag }}
			<div class="nat_dropzone">
				<div id="newservice">
					<div class="img_add proxynow addicon"></div>
					<div class="img_folder proxynow foldericon"></div>
				</div>
				<div id="id_newservice" class="nat_box">
					{% if o.host %}
					<div id="newsrv_{{ o.newService.id }}" class="list_item">
						<div class="proxynow trashicon item_delete" onclick="return natpf.remove_newservice(this)"></div>
						<div class="proxynow editicon item_edit" onclick="return natpf.edit_newservice(this)"></div>
						<div>{{ o.newService.get_html_repr }}</div>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<hr/>
		<div class="row">
			{{ form.comment.label_tag }}
			{{ form.comment }}
		</div>
		{% include "save_button.html" %}
		<div id="dialog-add-orgport" title="{{ dialog1_title }}">
			<div id="dialog_body-orgport"></div>
		</div>
		<div id="dialog-edit-orgport" title="{{ dialog1_edit_title }}">
			<div id="dialog_edit_body-orgport"></div>
		</div>
		<div id="dialog-add-host" title="{{ dialog2_title }}">
			<div id="dialog_body-host"></div>
		</div>
		<div id="dialog-edit-host" title="{{ dialog2_edit_title }}">
			<div id="dialog_edit_body-host"></div>
		</div>
		<div id="dialog-add-newservice" title="{{ dialog3_title }}">
			<div id="dialog_body-newservice"></div>
		</div>
		<div id="dialog-edit-newservice" title="{{ dialog3_edit_title }}">
			<div id="dialog_edit_body-newservice"></div>
		</div>
	</form>
</div>